# Generated by Django 2.2.2 on 2019-07-17 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_curso', '0002_auto_20190715_2028'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image_post',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
